#####
## NOTE
##
## This file is sealed, commited and pushed as part of the bootstrap process
## The unsealed version should NEVER be committed to git
#####

---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-credentials
  namespace: capi-self
  labels:
    # This is an essential label which allows the secret to be watched by manifests
    # which are dependent on the cluster-example-credentials secret.
    # If the secret has been applied to the `cloud-config` secret but you still have issues
    # with pods not being able to use the secret, you likely need to restart that pod.
    addons.stackhpc.com/watch: "true"
  annotations:
    # Allow the sealed secret controller to take over this secret after bootstrapping
    sealedsecrets.bitnami.com/managed: "true"
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: "<auth url>"
          application_credential_id: "<app cred id>"
          application_credential_secret: "<app cred secret>"
          project_id: "<project id>"
        region_name: "<region name>"
        interface: "public"
        identity_api_version: 3
        auth_type: "v3applicationcredential"
