---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-api-operator
  namespace: capi-operator-system
spec:
  url: https://kubernetes-sigs.github.io/cluster-api-operator
  interval: 1h
