---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-api-janitor-openstack
  namespace: capi-janitor-system
spec:
  url: https://stackhpc.github.io/cluster-api-janitor-openstack
  interval: 1h
