---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  chart: sealed-secrets
  version: 2.15.4
  sourceRef:
    kind: HelmRepository
    name: sealed-secrets
  interval: 1h
