---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-config
  namespace: flux-system
data:
  values.yaml: |
    # Install the CRDs
    installCRDs: true

    # We don't need the image automation at the moment
    imageAutomationController:
      create: false
    imageReflectionController:
      create: false
