---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: flux-system
spec:
  url: https://fluxcd-community.github.io/helm-charts
  interval: 1h
