---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-config
  namespace: cert-manager
data:
  values.yaml: |
    logLevel: 6
    prometheus:
      enabled: true
      servicemontior:
        enabled: true
        namespace: monitoring
        interval: 30s
    installCRDs: true
    config:
      enableGatewayAPI: true
