---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-operator
  namespace: opensearch
spec:
  chart:
    spec:
      chart: opensearch-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: opensearch-operator
        namespace: flux-system
      version: 2.7.0
      interval: 1m
  interval: 1m0s
  install:
    crds: CreateReplace
