---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault-dev
spec:
  chart:
    spec:
      chart: vault
      version: "0.30.1"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 30m
  interval: 60m
  install:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-dev
spec:
  interval: 5m
  dependsOn:
    - name: vault
  chart:
    spec:
      chart: vault-secrets-operator
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 1m
  values:
    defaultVaultConnection:
      enabled: true
      address: https://vault-dev.dafni.rl.ac.uk:8200
      caCertSecret: vault-prod-ca-cert
    defaultAuthMethod:
      enabled: true
      kubernetes:
        role: "vault-secrets-operator"
