---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ls-dev-cluster-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgBmdIE3uH2l4SaT5fHQ832lvVSP2TdkaGUZYH8B7iurWFHC8qzTbJoO3xgN09XyuFcDpceJuG8jSx4/rdZXSOpfS+QFw7Hl7wNkj20COPvdjZyvwvCdZ10mFGlRMhcmqUKFGXDYjZcmqs0iKB24J9n/bk6gtkLaAYRkBq8R7PXHZaxkvekSef710CA9Y88h7KrsIuYqVpTI78jhhHkWQOEnK3nt0KQCjxfi1L5Sa843BDcnrSz8OZMzD/WrRC/k5OHorg/C8VMqqDxR51ZZgj08xymvNAnZtVQolfj/ywgQKY7ZHHhZ6sG+uIo5glCUpvC+aUTUyAKcIhiFTZf5RprTeqv4pohEyAYsCy5ema3h6m1L+kjUKIOYHG8XaV6BaiSDj3D2tmAapc62dotLLoOhG15pYYM3HITUd1ekaQ93CKWU94sHvvYyj5ZyJnkyBMKiNxf0EaNETLJk6+TumbYIVdEX/6CwLxXQ6Zm8F8koiZmSydWDgwLwCgoqwqRYsg6zaaqAYFSgIk414bt04E0V9np9Y/eH8zzMCO9HVfKDHS4cc9JmRw7Gu0eV4zUxC6j4nVMW/ZAN83db6L2dhYfawjxu+tfnJNFE4Me0gtjw7nonnvuw2vnxFJR4cuBWRZ0NyZ7kentT7ImQysvoX6uhbIY5EZdH3TkN32LsNgi5jGWSmWC1FR9w4qd7dntB+jyLRDasoPxlLBinphovtE3L7zh36wsad35VDW+rHZXxgJdfN44YFBegfYY93++1R1ODKJiLcy2obCLBMo1QTNvsbp1unzt3lakhP444AP4Yx6ku9kwARxA9gtYFZaxK8B6hGTdPXoBDB5gwT/ZwO25J8sx5RiF8mY7FjaXRSSkodx6/kc0Vys/WbfiI8WpbpoQ8MM6AVcvuVcdJLj5JJBNRd3sC5jcMbUTHqjaL+IaWywSs6BCHASxOK3XaMFVMxFjJUHmmZhDHV8PlxDCMtaAsjMiBGRtIRohEUd00ZThUcUcIHL7CK+G4now7OiM83VSCTDksAOT6D9J/XqpyPftaqX3CHQZLPH1hChdzyJIdtqA+eLFTc+uZYbaGyeQjn/+BLFvy389sEyPnIKJINC1gzV18fM+orndoYvJl3N9XgwfBx+HiMz8EeLU9IhgyyOkxtj+QFLvNt7U6AwlQebw5WvZ4qXAcGE22JcYUKuUAke8Ia0+d3yhHcGSGILKcDhTs+ex5m/mG449avaYeQIrlGTngFzsCVRJlqHY9vwog4fAoKSZfdaHFpz+l/J8qLu/epcwYcDRx6Qmo63mHKnghR78yTnNTeQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        addons.stackhpc.com/watch: "true"
      name: ls-dev-cluster-credentials
      namespace: capi-self
